%% Create ToolboxToolbox configuration for AssetIOToolbox.

config = [ ...
    tbToolboxRecord( ...
    'name', 'MagicInputParser', ...
    'type', 'include'), ...
    tbToolboxRecord( ...
    'name', 'VirtualScenesExampleAssets', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox/VirtualScenesExampleAssets.git'), ...
    tbToolboxRecord( ...
    'name', 'AssetIOToolbox', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox/AssetIOToolbox.git', ...
    'localHookTemplate', 'aioMachineSetup.m'), ...
    ];

pathHere = fileparts(mfilename('fullpath'));
configPath = fullfile(pathHere, 'aioToolboxConfig.json');
tbWriteConfig(config, 'configPath', configPath);
