%% Create ToolboxToolbox configuration for VirtualScenesAssets.

config = [ ...
    tbToolboxRecord( ...
    'name', 'MagicInputParser', ...
    'type', 'include'), ...
    tbToolboxRecord( ...
    'name', 'VirtualScenesExampleAssets', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox/VirtualScenesExampleAssets.git'), ...
    tbToolboxRecord( ...
    'name', 'VirtualScenesAssets', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox/VirtualScenesAssets.git', ...
    'localHookTemplate', 'vsaMachineSetup.m'), ...
    ];

pathHere = fileparts(mfilename('fullpath'));
configPath = fullfile(pathHere, 'vsaToolboxConfig.json');
tbWriteConfig(config, 'configPath', configPath);
